### ISSUE TITLE
Connection refused problem

### ISSUE THREAD

**Issue by eranfain** [jcsilva/docker-kaldi-gstreamer-server#20]
Hi,
I have made everything as described in the practical example.
When I use the websocket client and check for status I get the appropriate answer, but when I apply:

python /tmp/client.py -u ws://localhost:8080/client/ws/speech -r 32000 /tmp/1272-128104-0000.wav

I get the following exception:

Traceback (most recent call last):
  File "/tmp/client.py", line 127, in <module>
    main()
  File "/tmp/client.py", line 122, in main
    ws.connect()
  File "/usr/local/lib/python2.7/dist-packages/ws4py/client/__init__.py", line 209, in connect
    self.sock.connect(self.bind_addr)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 111] Connection refused

Any help would be appreciated.

**Comment by jcsilva** [comment]
Hi,

For running the client example, you must install ws4py version 0.3.2. This can be installed using pip install --user ws4py==0.3.2. You may also need simplejson and pyaudio. They may also be installed using pip.

**Comment by eranfain** [comment]
I found the solution.
For some reason, it works with
python /tmp/client.py -u ws://172.17.0.1:8888/client/ws/speech -r 8192 /tmp/bill_gates-TED.mp3 

(The "localhost" was replaced with an IP address)

Thank you!
